# Generated by Django 5.2.1 on 2025-06-01 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Услуга оказана')], default='pending', max_length=50, verbose_name='Статус')),
                ('appointment_date', models.DateTimeField(verbose_name='Дата приёма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус записи')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Рекомендации')),
                ('general_comments', models.TextField(blank=True, null=True, verbose_name='Общие комментарии')),
            ],
            options={
                'verbose_name': 'Результат диагностики',
                'verbose_name_plural': 'Результаты диагностики',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='medical/', verbose_name='Фотография')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность')),
                ('experience', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стаж работы')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема обращения')),
                ('feedback', models.CharField(max_length=500, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_from_the_main_page', models.TextField(blank=True, null=True, verbose_name='Информация с главной страницы')),
                ('image_the_main_page', models.ImageField(blank=True, null=True, upload_to='medical/', verbose_name='Фото с главной страницы')),
                ('company_history', models.TextField(blank=True, null=True, verbose_name='История компании со страницы "О компании"')),
                ('mission', models.CharField(blank=True, max_length=100, null=True, verbose_name='Миссия со страницы "О компании"')),
                ('purposes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цели со страницы "О компании"')),
                ('image_from_the_company', models.ImageField(blank=True, null=True, upload_to='medical/', verbose_name='Фото со страницы "О компании"')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес центральной клиники')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название услуги')),
                ('description', models.CharField(max_length=500, verbose_name='Описание услуги')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('norm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Норма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
        ),
    ]
