# Generated by Django 5.2.1 on 2025-06-01 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='diagnosticresults',
            name='appointment',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.appointment', verbose_name='Запись'),
        ),
        migrations.AddField(
            model_name='diagnosticresults',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.doctors', verbose_name='Доктор'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели'),
        ),
        migrations.AddField(
            model_name='information',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели'),
        ),
        migrations.AddField(
            model_name='services',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший этот экземпляр модели'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.services', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='diagnostic_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='medical.diagnosticresults'),
        ),
    ]
